### ISSUE TITLE
Hyperlink for paper

### ISSUE THREAD

**Issue by BhargavJhaveri** [SoftwareEngineeringToolDemos/FSE-2012-MayPar#1]
The hyperlink should be only for the "paper". Not for "this paper." [writing-mechanics]

**Comment by BhargavJhaveri** [comment]
Updated hyperlink label

**Comment by Kavit900** [comment]
But the link provided in my Readme file goes to the same link which you have updated as - http://dl.acm.org/citation.cfm?id=2393611
