### ISSUE TITLE
Internal Binary link

### ISSUE THREAD

**Issue by BhargavJhaveri** [SoftwareEngineeringToolDemos/FSE-2012-MayPar#3]
Does the readme link to binary in this repo? [internal-binary]

This is missing in the readme file.

**Comment by BhargavJhaveri** [comment]
Update labels.

**Comment by Kavit900** [comment]
I updated the correct link for binary, this was the correct link - https://github.com/SoftwareEngineeringToolDemos/FSE-2012-MayPar/blob/master/MayPar/bin/MayPar
